stages:                              # Define the stages in your pipeline
  - .pre
  - build
  - test
  - deploy
  - release                          # Add the release stage
  - .post

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG             # Run this job when a tag is created
  script:
    - echo "running release_job"
    - zip -r source_code.zip .       # Create a zip file of the source code
  artifacts:                         # Specify artifacts at the job level
    paths:
      - source_code.zip              # Specify the zip file as an artifact
  release:
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    assets:
      links:
        - name: "Source Code"
          url: "https://gitlab.com/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/download"  # URL to download the artifacts