stages:                              # Define the stages in your pipeline
  - .pre
  - build
  - test
  - deploy
  - release                          # Add the release stage
  - .post

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest  # Use the release-cli image
  rules:
    - if: $CI_COMMIT_TAG             # Run this job when a tag is created
  script:
    - apk add --no-cache zip          # Install zip utility
    - echo "running release_job"
    - zip -r jhon-vault.zip .       # Create a zip file of the source code
    - release-cli create --description "$CI_COMMIT_TAG" --tag-name "$CI_COMMIT_TAG" --assets-link "{\"url\":\"https://gitlab.com/$CI_PROJECT_PATH/-/jobs/$CI_JOB_ID/artifacts/download\",\"name\":\"Source Code\"}"
  artifacts:                         # Specify artifacts at the job level
    paths:
      - jhon-vault.zip              # Specify the zip file as an artifact